tskit-dev/tstrait

.github/workflows/tests.yml, requirements/CI-tests-pip/requirements.txt
Simple testing workflow. To be improved.
=> setup github actions

requirements/CI-docs/requirements.txt, requirements/CI-tests-pip/requirements.txt
fix missing requirement for pip tests and add requirements for docs.
=> add requirements

.circleci/config.yml, .codecov.yaml, requirements/CI-complete/requirements.txt
setup circleci to track coverage (see #28).
=> setup circleci

.mergify.yml
=> add mergify.yml

.github/workflows/tests.yml
generate coverage report with github actions
=> update test workflow

tests/test_simulate_phenotype.py, tests/test_trait_model.py, tstrait/__init__.py, tstrait/simulate_phenotype.py, tstrait/trait_model.py
Update trait model to incorporate multiple distributions.
=> Update trait model

tests/test_sim_trait.py, tests/test_trait_model.py, tstrait/__init__.py, tstrait/simulate_effect_size.py, tstrait/trait_model.py
Add functionalities to simulate multiple traits from a multivariate normal distribution, and incorporate suggestions made in https://github.com/tskit-dev/tstrait/issues/54.
=> Multiple trait

tests/test_simulate_phenotype.py, tstrait/__init__.py, tstrait/simulate_phenotype.py
Create a function `sim_phenotype` to simulate phenotype based on existing functions.
=> simulate phenotype

CHANGELOG.md, docs/CHANGELOG.md, docs/_toc.yml, docs/release/index.md, docs/release/v0.0.1.md
Updates for version 0.0.1a2 release.
=> DOC: Version 0.0.1a2 update

docs/CHANGELOG.md, docs/_toc.yml, docs/release/index.md, docs/release/v0.0.1.md
=> DOC: Symbolic links

.github/workflows/wheels.yml
Release "master" has been sunset, need to specify a release version
=> Update release version

.github/workflows/docs.yml, CHANGELOG.md, docs/Makefile, docs/_config.yml
=> DOC: Version 0.0.1 update

tests/test_genetic_value.py, tstrait/genetic_value.py
Raise an error when there are no individuals.
Issue raised in https://github.com/tskit-dev/tstrait/issues/95
=> CODE: No individual

docs/effect-size.md
Add a short description about ploidy inside the documentation.
https://github.com/tskit-dev/tstrait/issues/95
=> DOC: Ploidy

tests/test_trait_model.py, tstrait/trait_model.py
Extend the fixed value trait model to simulate effect sizes from opposing signs.
=> CODE: Negative value

tests/data.py, tests/test_sim_trait.py, tstrait/simulate_effect_size.py
Update the sim_trait function.
=> CODE: sim_trait

docs/effect-size.md, tstrait/simulate_effect_size.py
Updated documentation for the new `sim_trait` function.
=> DOC: Documentation for the new sim_trait function

tests/test_trait_model.py, tstrait/trait_model.py
Update the docstring of trait model, as it will be used in the documentation to explain the corresponding model.
=> DOC: Docstring of trait model

tstrait/genetic_value.py, tstrait/simulate_effect_size.py
=> CODE: codecov

tests/test_simulate_environment.py, tests/test_simulate_phenotype.py, tstrait/simulate_effect_size.py, tstrait/simulate_environment.py, tstrait/simulate_phenotype.py
Update signature of `sim_trait`, `sim_env`, and `sim_phenotype`.
=> CODE: Signature

docs/effect-size.md, docs/environment.md, docs/genetic.md, docs/multi-trait.md, docs/quick-start.md
Minor changes to documentation
=> DOC: Minor changes

tests/test_sim_trait.py, tests/test_simulate_phenotype.py, tstrait/simulate_effect_size.py, tstrait/simulate_phenotype.py
Add option to simulate causal sites by indicating the causal site IDs
=> CODE: causal_sites

verification.py
Add multithreading in `validation.py`.
=> INFRA: multithreading

docs/effect-size.md, docs/genetic.md
Documentation for modifying the numericalisation of genotypes
=> DOC: Numericalisation-genotype

docs/api.md, docs/genetic.md, tests/test_genetic_value.py, tests/test_simulate_phenotype.py, tstrait/__init__.py, tstrait/genetic_value.py
Add new function to normalise genetic value
=> CODE: normalise_genetic_value

docs/citation.md
=> DOC: Citation

tstrait/genetic_value.py
Decouples the computation of genetic values from output in terms of individuals to enable later generalisations.
cc @gregorgorjanc
=> Generalise the traversal algorithm to return node values
